baseURL = 'https://madhavkhoslaa.github.io/'
languageCode = 'en-us'
title = 'Madhav Khosla'
theme = "archie"
[params]
	mode="dark" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "Backend Engineer | Crypto Enthusiast"

# Social Tags

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://bit.ly/3Qyr87Y"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://bit.ly/3Qtgn6y"

# [[params.social]]
# name = "GitLab"
# icon = "gitlab"
# url = "https://gitlab.com/athul/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
